#!/bin/bash

image_name=$1
container_name=$2
deap_version_tag=$3
port=$4

USAGE="Usage: run <image ID / name:tag> <container name> <DEAP git version tag> <port>"

if [[ $# -eq 4 ]]; then
    docker run -d \
               --name ${container_name} \
               -p ${port}:80 \
               -v data:/data \
               -v matlab:/matlab \
               ${image_name} \
               start
           #--restart unless-stopped \
else
    echo ${USAGE}
fi
